project:
  type: website

website:
  title: "title"
  page-navigation: true
  back-to-top-navigation: true
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, source, issue]
  navbar:
    search: true
    # left:
    #   - text: Index
    #     href: index.qmd
    # tools:
    #   - icon: github
    #     menu:
    #       - text: Source Code
    #         href:  https://code.com
    #       - text: Report a Bug
    #         href:  https://bugs.com
  sidebar:
    contents: auto
    style: "docked"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
  cache: true